-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-08-21 00:58:55 IST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking (
    booking_id   NUMBER NOT NULL,
    member_id    NUMBER NOT NULL,
    facility_id  NUMBER NOT NULL,
    booking_date DATE NOT NULL,
    start_time   VARCHAR2(10) NOT NULL,
    end_time     VARCHAR2(10) NOT NULL,
    status       VARCHAR2(20) NOT NULL,
    created_at   TIMESTAMP NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT pk_booking PRIMARY KEY ( booking_id );

CREATE TABLE facility (
    facility_id   NUMBER NOT NULL,
    sport_id      NUMBER NOT NULL,
    facility_name VARCHAR2(100) NOT NULL,
    description   VARCHAR2(255),
    location      VARCHAR2(150) NOT NULL,
    address       VARCHAR2(255),
    opening_time  VARCHAR2(10),
    closing_time  VARCHAR2(10),
    status        VARCHAR2(20) NOT NULL
);

ALTER TABLE facility ADD CONSTRAINT pk_facility PRIMARY KEY ( facility_id );

CREATE TABLE inquiry (
    inquiry_id NUMBER NOT NULL,
    member_id  NUMBER NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100) NOT NULL,
    subject    VARCHAR2(150) NOT NULL,
    message    VARCHAR2(1000) NOT NULL,
    status     VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE inquiry ADD CONSTRAINT pk_inquiry PRIMARY KEY ( inquiry_id );

CREATE TABLE member (
    member_id  NUMBER NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(150) NOT NULL,
    phone      VARCHAR2(20),
    password   VARCHAR2(255) NOT NULL,
    status     VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE member ADD CONSTRAINT pk_member_id PRIMARY KEY ( member_id );

CREATE TABLE member_sport (
    member_id NUMBER NOT NULL,
    sport_id  NUMBER NOT NULL,
    joined_at TIMESTAMP NOT NULL
);

ALTER TABLE member_sport ADD CONSTRAINT pk_member_sport PRIMARY KEY ( member_id,
                                                                      sport_id );

CREATE TABLE review (
    review_id    NUMBER NOT NULL,
    member_id    NUMBER NOT NULL,
    facility_id  NUMBER NOT NULL,
    rating       NUMBER NOT NULL,
    comment_text VARCHAR2(500),
    created_at   TIMESTAMP NOT NULL
);

ALTER TABLE review ADD CONSTRAINT pk_review PRIMARY KEY ( review_id );

CREATE TABLE sport (
    sport_id    NUMBER NOT NULL,
    sport_name  VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

ALTER TABLE sport ADD CONSTRAINT pk_sport PRIMARY KEY ( sport_id );

ALTER TABLE sport ADD CONSTRAINT uq_sport_name UNIQUE ( sport_name );

ALTER TABLE booking
    ADD CONSTRAINT booking_facility_fk FOREIGN KEY ( facility_id )
        REFERENCES facility ( facility_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE facility
    ADD CONSTRAINT facility_sport_fk FOREIGN KEY ( sport_id )
        REFERENCES sport ( sport_id );

ALTER TABLE inquiry
    ADD CONSTRAINT inquiry_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE member_sport
    ADD CONSTRAINT member_sport_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE member_sport
    ADD CONSTRAINT member_sport_sport_fk FOREIGN KEY ( sport_id )
        REFERENCES sport ( sport_id );

ALTER TABLE review
    ADD CONSTRAINT review_facility_fk FOREIGN KEY ( facility_id )
        REFERENCES facility ( facility_id );

ALTER TABLE review
    ADD CONSTRAINT review_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
