-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-08-23 18:44:03 IST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



CREATE USER sports_booking IDENTIFIED BY account

unlock;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE sports_booking.booking (
    booking_id   NUMBER NOT NULL,
    member_id    NUMBER NOT NULL,
    facility_id  NUMBER NOT NULL,
    booking_date DATE NOT NULL,
    start_time   VARCHAR2(10 BYTE) NOT NULL,
    end_time     VARCHAR2(10 BYTE) NOT NULL,
    status       VARCHAR2(20 BYTE) NOT NULL,
    created_at   TIMESTAMP NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_booking ON
    sports_booking.booking (
        booking_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.booking
    ADD CONSTRAINT pk_booking PRIMARY KEY ( booking_id )
        USING INDEX sports_booking.pk_booking;

CREATE TABLE sports_booking.facility (
    facility_id   NUMBER NOT NULL,
    sport_id      NUMBER NOT NULL,
    facility_name VARCHAR2(100 BYTE) NOT NULL,
    description   VARCHAR2(255 BYTE),
    location      VARCHAR2(150 BYTE) NOT NULL,
    address       VARCHAR2(255 BYTE),
    opening_time  VARCHAR2(10 BYTE),
    closing_time  VARCHAR2(10 BYTE),
    status        VARCHAR2(20 BYTE) NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_facility ON
    sports_booking.facility (
        facility_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.facility
    ADD CONSTRAINT pk_facility PRIMARY KEY ( facility_id )
        USING INDEX sports_booking.pk_facility;

CREATE TABLE sports_booking.inquiry (
    inquiry_id NUMBER NOT NULL,
    member_id  NUMBER NOT NULL,
    name       VARCHAR2(100 BYTE) NOT NULL,
    email      VARCHAR2(100 BYTE) NOT NULL,
    subject    VARCHAR2(150 BYTE) NOT NULL,
    message    VARCHAR2(1000 BYTE) NOT NULL,
    status     VARCHAR2(20 BYTE) NOT NULL,
    created_at TIMESTAMP NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_inquiry ON
    sports_booking.inquiry (
        inquiry_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.inquiry
    ADD CONSTRAINT pk_inquiry PRIMARY KEY ( inquiry_id )
        USING INDEX sports_booking.pk_inquiry;

CREATE TABLE sports_booking.member (
    member_id  NUMBER NOT NULL,
    name       VARCHAR2(100 BYTE) NOT NULL,
    email      VARCHAR2(150 BYTE) NOT NULL,
    phone      VARCHAR2(20 BYTE),
    password   VARCHAR2(255 BYTE) NOT NULL,
    status     VARCHAR2(20 BYTE) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_role  VARCHAR2(20 BYTE) DEFAULT 'Member' NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_member_id ON
    sports_booking.member (
        member_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.member
    ADD CONSTRAINT pk_member_id PRIMARY KEY ( member_id )
        USING INDEX sports_booking.pk_member_id;

CREATE TABLE sports_booking.member_sport (
    member_id NUMBER NOT NULL,
    sport_id  NUMBER NOT NULL,
    joined_at TIMESTAMP NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_member_sport ON
    sports_booking.member_sport (
        member_id
    ASC,
        sport_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.member_sport
    ADD CONSTRAINT pk_member_sport
        PRIMARY KEY ( member_id,
                      sport_id )
            USING INDEX sports_booking.pk_member_sport;

CREATE TABLE sports_booking.review (
    review_id    NUMBER NOT NULL,
    member_id    NUMBER NOT NULL,
    facility_id  NUMBER NOT NULL,
    rating       NUMBER NOT NULL,
    comment_text VARCHAR2(500 BYTE),
    created_at   TIMESTAMP NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_review ON
    sports_booking.review (
        review_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                PCTINCREASE
            0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.review
    ADD CONSTRAINT pk_review PRIMARY KEY ( review_id )
        USING INDEX sports_booking.pk_review;

CREATE TABLE sports_booking.sport (
    sport_id    NUMBER NOT NULL,
    sport_name  VARCHAR2(50 BYTE) NOT NULL,
    description VARCHAR2(255 BYTE)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX sports_booking.pk_sport ON
    sports_booking.sport (
        sport_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

CREATE UNIQUE INDEX sports_booking.uq_sport_name ON
    sports_booking.sport (
        sport_name
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE (
                INITIAL
            65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sports_booking.sport
    ADD CONSTRAINT pk_sport PRIMARY KEY ( sport_id )
        USING INDEX sports_booking.pk_sport;

ALTER TABLE sports_booking.sport
    ADD CONSTRAINT uq_sport_name UNIQUE ( sport_name )
        USING INDEX sports_booking.uq_sport_name;

ALTER TABLE sports_booking.booking
    ADD CONSTRAINT booking_facility_fk
        FOREIGN KEY ( facility_id )
            REFERENCES sports_booking.facility ( facility_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.booking
    ADD CONSTRAINT booking_member_fk
        FOREIGN KEY ( member_id )
            REFERENCES sports_booking.member ( member_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.facility
    ADD CONSTRAINT facility_sport_fk
        FOREIGN KEY ( sport_id )
            REFERENCES sports_booking.sport ( sport_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.inquiry
    ADD CONSTRAINT inquiry_member_fk
        FOREIGN KEY ( member_id )
            REFERENCES sports_booking.member ( member_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.member_sport
    ADD CONSTRAINT member_sport_member_fk
        FOREIGN KEY ( member_id )
            REFERENCES sports_booking.member ( member_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.member_sport
    ADD CONSTRAINT member_sport_sport_fk
        FOREIGN KEY ( sport_id )
            REFERENCES sports_booking.sport ( sport_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.review
    ADD CONSTRAINT review_facility_fk
        FOREIGN KEY ( facility_id )
            REFERENCES sports_booking.facility ( facility_id )
            NOT DEFERRABLE;

ALTER TABLE sports_booking.review
    ADD CONSTRAINT review_member_fk
        FOREIGN KEY ( member_id )
            REFERENCES sports_booking.member ( member_id )
            NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             8
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
