using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SportsBooking.API.Models;

public partial class SportsBookingDbContext : DbContext
{
    public SportsBookingDbContext()
    {
    }

    public SportsBookingDbContext(
        DbContextOptions<SportsBookingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Facility> Facilities { get; set; }

    public virtual DbSet<Inquiry> Inquiries { get; set; }
    public virtual DbSet<InquiryResponse> InquiryResponses { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberSport> MemberSports { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Sport> Sports { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("SPORTS_BOOKING")
            .UseCollation("USING_NLS_COMP");

        // Booking IDs and created time are generated by the database
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.Property(e => e.BookingId)
                .ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt)
                .ValueGeneratedOnAdd();

            entity.HasOne(d => d.Facility)
                .WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("BOOKING_FACILITY_FK");

            entity.HasOne(d => d.Member)
                .WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("BOOKING_MEMBER_FK");
        });

        // Facility ID is generated by the database
        modelBuilder.Entity<Facility>(entity =>
        {
            entity.Property(e => e.FacilityId)
                .ValueGeneratedOnAdd();

            entity.HasOne(d => d.Sport)
                .WithMany(p => p.Facilities)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FACILITY_SPORT_FK");
        });

        // Inquiry ID and created time are generated by the database
        modelBuilder.Entity<InquiryResponse>(entity =>
        {
            entity.HasKey(e => e.ResponseId);

            entity.Property(e => e.ResponseId)
                .ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt)
                .ValueGeneratedOnAdd();

            entity.HasOne(d => d.Inquiry)
                .WithMany(p => p.Responses)
                .HasForeignKey(d => d.InquiryId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_INQUIRY_RESPONSE_INQUIRY");
        });

        // Member ID and created time are generated by the database
        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId)
                .HasName("PK_MEMBER_ID");

            entity.Property(e => e.MemberId)
                .ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt)
                .ValueGeneratedOnAdd();
        });

        // MemberSport uses member and sport IDs as its key
        modelBuilder.Entity<MemberSport>(entity =>
        {
            entity.HasOne(d => d.Member)
                .WithMany(p => p.MemberSports)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("MEMBER_SPORT_MEMBER_FK");

            entity.HasOne(d => d.Sport)
                .WithMany(p => p.MemberSports)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("MEMBER_SPORT_SPORT_FK");

            entity.Property(e => e.JoinedAt)
                .ValueGeneratedOnAdd();
        });

        // Review ID and created time are generated by the database
        modelBuilder.Entity<Review>(entity =>
        {
            entity.Property(e => e.ReviewId)
                .ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt)
                .ValueGeneratedOnAdd();

            entity.HasOne(d => d.Facility)
                .WithMany(p => p.Reviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("REVIEW_FACILITY_FK");

            entity.HasOne(d => d.Member)
                .WithMany(p => p.Reviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("REVIEW_MEMBER_FK");
        });

        // Sport ID is generated by the database
        modelBuilder.Entity<Sport>(entity =>
        {
            entity.HasKey(e => e.SportId);

            entity.Property(e => e.SportId)
                .ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}